from datetime import datetime
from typing import List, Tuple, Union

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, Frame, PageTemplate
import os
import re
import textwrap
from fastapi.responses import FileResponse

from document.document_structure import PlanContent
from integration.GCPClientBucket import StorageClientWrapper
from document.MultiAgent.base_document_generator import BaseDocumentGenerator


class PDFGenerator(BaseDocumentGenerator):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.styles = getSampleStyleSheet()
        self._add_custom_styles()

    def generate_pdf(self, title, plan_content: PlanContent, layout_type="two_column"):
        file_name = f"{title.replace(' ', '_')}.pdf"
        file_path = os.path.join("pdfs", file_name)
        os.makedirs("pdfs", exist_ok=True)

        document = SimpleDocTemplate(file_path, pagesize=A4)
        document.title = title

        width, height = A4
        frame = Frame(0, 0, width, height - 100, id='normal')  # Leave space for the title page

        custom_page_template = PageTemplate(id='title', onPage=self.add_title_page, frames=[frame])
        document.addPageTemplates([custom_page_template])
        elements = []
        layout_type = "two_column"
        # 1page print ->

        strategic_overview = plan_content.mission_overview

        print(strategic_overview)
        parsed_strategic_overview = self.extract_headers_and_subpoints(strategic_overview)
        print(parsed_strategic_overview)

        three_content_data = [
            (f"Phase {index + 1}", str(phase.phase).strip(), [str(obj.objective).strip() for obj in phase.objectives])
            for index, phase in enumerate(plan_content.phases)
        ]

        elements.append(PageBreak())
        self._add_single_column(elements, ("Strategic Project Overview:", parsed_strategic_overview))
        elements.append(PageBreak())
        self._add_three_column(elements, three_content_data)
        elements.append(PageBreak())

        content_data = [
            (objective.objective.title(), "\n".join(sub_point for sub_point in objective.sub_points))
            for phase in plan_content.phases
            for objective in phase.objectives
        ]

        self._add_two_column(elements, content_data)

        #self._add_table(elements, content_data)


        # if layout_type == "single":
        #     self._add_single_column(elements, content_data)
        # elif layout_type == "two_column":
        #     self._add_two_column(elements, content_data)


        # Saving - processes after

        document.build(elements)
        storage_client_wrapper = StorageClientWrapper()
        storage_client_wrapper.upload_file(title, file_path)

        return FileResponse(file_path, media_type="application/pdf", filename=file_name)

    def add_title_page(self, canvas, doc):
        # Get page dimensions
        width, height = A4

        # Set navy blue background
        canvas.setFillColor(HexColor("#263D48"))
        canvas.rect(0, 0, width, height, fill=True, stroke=False)

        # Set text properties
        canvas.setFillColor(colors.white)  # White text for contrast
        canvas.setFont("Helvetica-Bold", 24)

        # Add Title (Centered at the top)
        title = doc.title
        max_width = 80  # Adjust based on font size and page width
        wrapped_title = textwrap.wrap(title, width=max_width)  # Break into lines

        # Start drawing each line from the top, moving downward for each line
        y_position = height - 100
        for line in wrapped_title:
            canvas.drawCentredString(width / 2, y_position, line)
            y_position -= 20  # Adjust line spacin

        # Add Date (Below title)
        canvas.setFont("Helvetica", 14)
        current_date = datetime.now().strftime("%B %d, %Y")  # Format: February 11, 2025
        canvas.drawCentredString(width / 2, height - 140, f"Date: {current_date}")

        # Add Generation Info (Below date)
        canvas.setFont("Helvetica-Oblique", 12)
        canvas.drawCentredString(width / 2, height - 170, "Generated by Authentic Scope")
